### ISSUE TITLE
Upload local file to Gravatar

### ISSUE THREAD

**Issue by SupasitW** [ruddfawcett/random-gravatar#1]
I used the code and I changed the class `Randomizer` to upload new local image to Gravatar.

``` php
public function randomizeGravatar()  {
  // Let's keep our API classes here...
  $gravatarAPI = new GravatarRPC("MyAPiKey", "MyEmail");
  $octodexAPI = new Octodex();

  $data = file_get_contents($_SERVER['DOCUMENT_ROOT']."/gravatar/profile.png");
  $gravatarAPI->saveData($data,0);
}
```

but I got error below

> Fatal error : **Uncaught exception** 'GravatarException' with message 'Could not fetch file' in C:\xampp\htdocs\gravatar\classes\GravatarRPC.class.php:82 Stack trace: #0 C:\xampp\htdocs\gravatar\classes\GravatarRPC.class.php(142): GravatarRPC->call('saveData', Array) #1 C:\xampp\htdocs\gravatar\classes\randomizer.php(19): GravatarRPC->saveData('\x89PNG\r\n\x1A\n\x00\x00\x00\rIHD...', 0)

Could you please give me an example to upload a new local profile picture to Gravatar?

**Comment by ruddfawcett** [comment]
Have you tried any debugging? What happens when you:

``` php
echo $data;
```

Is it a valid URL?

**Comment by SupasitW** [comment]
Yes, I try to debug `$data` using `echo $data;` and I found that it's a blob of my image (local image on my computer).

Example:

> �PNG  IHDRX,=͖   pHYs�� OiCCPPhotoshop ICC profilexڝSgTS�=���BK���KoR RB���&*!    J�!��Q�EEȠ�����Q,� ��!���������{�kּ������>��������H3Q5�

**Comment by ruddfawcett** [comment]
@SupasitW sorry, completely missed that you are using `file_get_contents()`. I was thinking just to see if the path to the URL is correct. In your case, clearly the fact _is correct_ as seen in your PNG blob, but you need to use the file from a web server, per the Gravatar API spec, I think. You can upload files to that server and then store them locally and point the Gravatar API to that file. 

Otherwise, your solution won't work, because you aren't actually directly uploading an image to Gravatar, just pointing it to a link the API can't read (as its local). Hope that helps.

**Comment by SupasitW** [comment]
Thank you, Rudd. Now I can upload picture to Gravatar by following your suggestion (upload files to that server, store them locally, and point the Gravatar API to that file).

Thank you for your help!

**Comment by ruddfawcett** [comment]
No problem! Glad you figured this out.
